openapi: 3.0.3
info:
  title: CleanCheeks REST APIs
  description: |-
    REST API for CleanCheeks backend
  version: 1.0.0
tags:
  - name: Toilets
    description: Toilets Database
  - name: Ratings
    description: Ratings for each toilet
  - name: Preferences
    description: Preferences for each toilet
  - name: user
    description: User Operations
    
paths:
  /api/v1/ratings:
    post:
      tags:
        - Ratings
      summary: Create a toilet rating
      description: Creating a toilet rating
      requestBody:
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRatingDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/CreateRatingDTO'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateRatingDTO'
        required: true
      responses:
        '200':
          description: Success
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
            application/xml:
              schema:
                $ref: '#/components/schemas/Rating'
        '400':
          description: Bad request
    get:
      tags:
        - Ratings
      summary: Get all toilet ratings
      description: Creating a toilet rating
      responses:
        '200':
          description: Success
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/RatingResponseArray'
        '400':
          description: Bad request
              
components:
  schemas:
    CreateRatingDTO:
      type: object
      required:
        - toilet_id
        - user_id
        - type
      properties:
        toilet_id:
          type: string
        user_id:
          type: string
        type:
          type: string
          enum: [CLEAN, DIRTY]
    Rating:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: Added rating
        data:
          type: object
          properties:
            id:
              type: string
            toilet_id:
              type: string
            user_id:
              type: string
            type:
              type: string
            updatedAt:
              type: string
            createdAt:
              type: string
    RatingResponseArray:
      type: array
      items:
        $ref: '#/components/schemas/Rating'
